services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: clouddeploy-app
    restart: always
    ports:
      - "${PORT:-5000}:${PORT:-5000}"
    env_file:
      - .env
    depends_on:
      - mongo
    networks:
      - proshop-network

  mongo:
    image: mongo:latest
    container_name: clouddeploy-mongo
    restart: always
    volumes:
      - mongo-data:/data/db
    networks:
      - proshop-network

volumes:
  mongo-data:
    driver: local

networks:
  proshop-network:
    driver: bridge
